### ISSUE TITLE
npm install fails with npm 4.2.1

### ISSUE THREAD

**Issue by mkubik** [rvagg/node-max31855pi#1]
Hi, runing npm i fails. See below:

npm install

> max31855pi@1.0.0 install /home/mk/grill/node_modules/max31855pi
> node-gyp rebuild

make: Entering directory '/home/mk/grill/node_modules/max31855pi/build'
  CC(target) Release/obj.target/max31855pi/src/bcm2835.o
  CXX(target) Release/obj.target/max31855pi/src/max31855.o
  CXX(target) Release/obj.target/max31855pi/src/node_max31855.o
In file included from ../src/node_max31855.cc:2:0:
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:672:67: note: candidates are:
In file included from /home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:25:0,
                 from ../src/node_max31855.cc:2:
/home/mk/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/mk/.node-gyp/4.2.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/mk/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/mk/.node-gyp/4.2.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/node_max31855.cc:2:0:
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), size)’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
/home/mk/grill/node_modules/max31855pi/node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
max31855pi.target.mk:94: recipe for target 'Release/obj.target/max31855pi/src/node_max31855.o' failed
make: *** [Release/obj.target/max31855pi/src/node_max31855.o] Error 1
make: Leaving directory '/home/mk/grill/node_modules/max31855pi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mk/grill/node_modules/max31855pi
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! max31855pi@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the max31855pi@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the max31855pi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs max31855pi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls max31855pi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mk/grill/npm-debug.log

**Comment by rvagg** [comment]
I don't have time to address this right now but if you want to give it a go yourself you'd just need to upgrade it to use NAN v2+ which is a bit of a change in the C++ code but you can use https://github.com/nodesource/upgrade-utils to do most of the work for you. I can help if you want to submit a work-in-progress pull request if you can't get it all working.
